baseurl: http://www.toddrjones.com/
title: Todd Jones
author: Todd Jones
canonifyurls: yes
languagecode: en
paginate: 3
theme: hugo-renga
enableEmoji: yes
hasCJKLanguage: yes
googleAnalytics: "UA-124811401-2"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
params:
  copyright: © 2021 Todd Jones
  copyrightUrl: http://www.toddrjones.com
  email: trj234@msstate.edu
  faviconfile: image/favicon.png
  #github: toddrjones
  highlightjs: yes
  #linkedin: 
  logofile: image/avatar.png
  pagetitle: Todd Jones
  posts_navigation: yes
  progressively: no
  twitter: toddrjones
  uselatex: yes
menu:
  primary:
    - identifier: research
      name: Research
      url: /research/
      weight: 1   
    - identifier: cv
      name: CV
      url: /cv/TJonesCV.pdf
      weight: 2
    - identifier: dataviz
      name: Data Visualization
      url: /dataviz/
      weight: 3     
    - identifier: blog
      name: Blog
      url: /blog/ 
      weight: 4        
    - identifier: personal
      name: Personal
      url: /personal/
      weight: 5  
#    - identifier: misc
#      name: Misc.
#      url: /misc/
#      weight: 6        
