baseurl = "http://www.toddrjones.com/"
title = "Todd Jones"
author = "Todd Jones"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

googleAnalytics = "UA-124811401-2"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Todd R. Jones"
copyright = "© 2021 Todd R. Jones"
copyrightUrl = "http://www.toddrjones.com/"
faviconfile = "image/favicon.png"
logofile = "image/avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

#github = "nanxstats"
twitter = "toddjones"
#linkedin = "nanxstats"
email = "trj234@msstate.edu"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2