#baseurl: http://www.toddrjones.com/
baseurl: /
title: Todd Jones
author: Todd Jones
canonifyurls: yes
languagecode: en
paginate: 3
theme: hugo-renga
enableEmoji: yes
hasCJKLanguage: yes
#googleAnalytics: "UA-124811401-2" (updated to ...-1; see 12/8/2021 email; not sure if this is right or not)
#googleAnalytics: "UA-124811401-2"
googleAnalytics: "G-GHSS434RRK"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  copyright: © 2025 Todd Jones
  copyrightUrl: http://www.toddrjones.com
  email: trj234@msstate.edu
  faviconfile: image/favicon.png
  #github: toddrjones
  highlightjs: yes
  #linkedin: 
  #logofile: image/avatar.png
  pagetitle: Todd Jones
  posts_navigation: yes
  progressively: no
  twitter: toddrjones
  uselatex: yes
menu:
  primary:
    - identifier: research
      name: Research
      url: /research/
      weight: 1   
    - identifier: cv
      name: CV
      url: /cv/
      weight: 2
    - identifier: quickstatatips
      name: Quick Stata Tips Book
      url: /quickstatatips/
      weight: 2
    - identifier: dataviz
      name: Data Visualization
      url: /dataviz/
      weight: 4     
    - identifier: blog
      name: Blog
      url: /blog/ 
      weight: 5        
    - identifier: personal
      name: Personal
      url: /personal/
      weight: 6  
#    - identifier: misc
#      name: Misc.
#      url: /misc/
#      weight: 6        

markup:
  goldmark:
    renderer:
      unsafe: true
